# Generated by Django 5.2.13 on 2026-05-07 17:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.contentcategory')),
            ],
            options={
                'verbose_name_plural': 'Content Categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('title_ch', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_ch', models.TextField(blank=True)),
                ('event_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=300)),
                ('location_link', models.URLField(blank=True)),
                ('is_virtual', models.BooleanField(default=False)),
                ('virtual_link', models.URLField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('title_ch', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(upload_to='gallery/covers/')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('caption_ch', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.gallery')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('name_ch', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('description_ch', models.TextField(blank=True)),
                ('leader', models.CharField(max_length=200)),
                ('leader_contact', models.CharField(blank=True, max_length=100)),
                ('meeting_day', models.CharField(blank=True, max_length=50)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ministries/')),
                ('order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ministries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScriptureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(blank=True, help_text='Optional title for the reading', max_length=200)),
                ('bible_verse', models.TextField(help_text='Full Bible verse text')),
                ('spirit_of_prophecy', models.TextField(help_text='Spirit of Prophecy/EGW text')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scripture Reading',
                'verbose_name_plural': 'Scripture Readings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('title_ch', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_ch', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('sermon', 'Sermon'), ('video', 'Video'), ('audio', 'Audio'), ('song', 'Song'), ('literature', 'Literature')], max_length=20)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('local_video', models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'mkv'])])),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a'])])),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('pdf_category', models.CharField(blank=True, choices=[('sabbath_school', 'Sabbath School Lessons'), ('week_of_prayer', 'Week of Prayer Readings'), ('marriage', 'Marriage Readings'), ('children', "Children's Ministry"), ('youth', 'Youth Ministry'), ('general', 'General Literature')], max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('speaker', models.CharField(blank=True, max_length=200)),
                ('bible_verses', models.CharField(blank=True, max_length=200)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='content.contentcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'publish_date'], name='content_con_content_c970b6_idx'), models.Index(fields=['pdf_category'], name='content_con_pdf_cat_8c6a30_idx')],
            },
        ),
    ]
