# Generated by Django 5.2.13 on 2026-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description_ch',
            field=models.TextField(blank=True, help_text='Chichewa translation of description'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_ch',
            field=models.CharField(blank=True, help_text='Chichewa translation of title', max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption_ch',
            field=models.CharField(blank=True, help_text='Chichewa translation of caption', max_length=200),
        ),
    ]
