# Generated by Django 5.2.13 on 2026-05-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_gallery_description_ch_alter_gallery_title_ch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='leader',
            field=models.CharField(blank=True, help_text='Leave blank if not applicable', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='leader_contact',
            field=models.CharField(blank=True, help_text='Leave blank if not applicable', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='meeting_day',
            field=models.CharField(blank=True, help_text='Leave blank if not applicable (e.g., for online-only ministries)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='meeting_time',
            field=models.TimeField(blank=True, help_text='Leave blank if not applicable', null=True),
        ),
    ]
