# Generated by Django 5.2.13 on 2026-05-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_ministry_leader_alter_ministry_leader_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Content Categories'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-event_date', '-created_at'], 'verbose_name_plural': 'Galleries'},
        ),
    ]
