# Generated by Django 5.2.13 on 2026-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_contentcategory_options_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripturereading',
            name='bible_verse_ch',
            field=models.TextField(blank=True, help_text='Full Bible verse text (Chichewa)', null=True),
        ),
        migrations.AddField(
            model_name='scripturereading',
            name='spirit_of_prophecy_ch',
            field=models.TextField(blank=True, help_text='Spirit of Prophecy/EGW text (Chichewa)', null=True),
        ),
        migrations.AddField(
            model_name='scripturereading',
            name='title_ch',
            field=models.CharField(blank=True, help_text='Optional title for the reading (Chichewa)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scripturereading',
            name='bible_verse',
            field=models.TextField(help_text='Full Bible verse text (English)'),
        ),
        migrations.AlterField(
            model_name='scripturereading',
            name='spirit_of_prophecy',
            field=models.TextField(help_text='Spirit of Prophecy/EGW text (English)'),
        ),
        migrations.AlterField(
            model_name='scripturereading',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title for the reading (English)', max_length=200),
        ),
    ]
