# Generated by Django 5.2.13 on 2026-05-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayerrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='servicetime',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='servicetime',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='ChurchLeadership',
        ),
        migrations.DeleteModel(
            name='PrayerRequest',
        ),
        migrations.DeleteModel(
            name='ServiceTime',
        ),
    ]
